package com.xiaorui.agentapplicationcreator.agent.orchestrator;

import cn.hutool.core.lang.UUID;
import cn.hutool.core.util.StrUtil;
import com.github.houbb.sensitive.word.core.SensitiveWordHelper;
import com.xiaorui.agentapplicationcreator.agent.creator.AgentAppCreator;
import com.xiaorui.agentapplicationcreator.agent.model.dto.AgentTaskStatus;
import com.xiaorui.agentapplicationcreator.agent.model.schema.SystemOutput;
import com.xiaorui.agentapplicationcreator.constant.AgentTaskConstant;
import com.xiaorui.agentapplicationcreator.enums.AppVersionSourceEnum;
import com.xiaorui.agentapplicationcreator.enums.AgentFailTypeEnum;
import com.xiaorui.agentapplicationcreator.enums.AgentTaskStatusEnum;
import com.xiaorui.agentapplicationcreator.execption.BusinessException;
import com.xiaorui.agentapplicationcreator.execption.ErrorCode;
import com.xiaorui.agentapplicationcreator.execption.ThrowUtil;
import com.xiaorui.agentapplicationcreator.model.entity.AgentTask;
import com.xiaorui.agentapplicationcreator.model.entity.User;
import com.xiaorui.agentapplicationcreator.service.AgentTaskService;
import com.xiaorui.agentapplicationcreator.service.AppVersionService;
import com.xiaorui.agentapplicationcreator.service.ChatHistoryService;
import com.xiaorui.agentapplicationcreator.service.UserService;
import com.xiaorui.agentapplicationcreator.service.UserThreadBindService;
import com.xiaorui.agentapplicationcreator.util.CodeFileSaverUtil;
import com.xiaorui.agentapplicationcreator.util.SecurityUtil;
import jakarta.annotation.Resource;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.Optional;
import java.util.Set;

import static com.xiaorui.agentapplicationcreator.enums.AgentTaskStatusEnum.RUNNING;
import static com.xiaorui.agentapplicationcreator.enums.AgentTaskStatusEnum.SUCCEEDED;

@Component
@Slf4j
public class DefaultAgentOrchestrator implements AgentOrchestrator {

    private static final String TASK_STATUS_INDEX_PREFIX = "task_status:";
    private static final Integer MAX_INPUT_LENGTH = 2000;

    @Resource
    private AgentAppCreator agentAppCreator;

    @Resource
    private AgentTaskExecutor agentTaskExecutor;

    @Resource
    private AgentTaskService agentTaskService;

    @Resource
    private UserService userService;

    @Resource
    private UserThreadBindService userThreadBindService;

    @Resource
    private ChatHistoryService chatHistoryService;

    @Resource
    private RedisTemplate<String, AgentTask> agentTaskRedisTemplate;

    @Resource
    private RedisTemplate<String, String> stringRedisTemplate;

    @Resource
    private CodeFileSaverUtil codeFileSaverUtil;

    @Resource
    private AppVersionService appVersionService;

    @Override
    public AgentTaskStatus handleUserMessage(String message, String threadId, String appId) {
        validateUserInput(message);

        String taskId = UUID.randomUUID().toString();
        String userId = SecurityUtil.getUserInfo().getUserId();
        User loginUser = userService.getById(userId);
        ThrowUtil.throwIf(loginUser == null, ErrorCode.NOT_FOUND_ERROR, "用户不存在");

        String updatedThreadId = Optional.ofNullable(threadId)
                .filter(StrUtil::isNotBlank)
                .orElse(UUID.randomUUID().toString());

        log.info("Agent task accepted, taskId={}, threadId={}, appId={}, userId={}",
                taskId, updatedThreadId, appId, userId);

        userThreadBindService.ensureThreadOwnership(userId, updatedThreadId, "app_creator_agent");

        agentTaskService.initTask(taskId, updatedThreadId, appId);
        chatHistoryService.saveChatHistory(appId, userId, message, "user");

        String finalUserId = userId;
        agentTaskExecutor.submitAgentTask(taskId, () -> {
            try {
                agentTaskService.updateStatus(taskId, RUNNING);
                SystemOutput output = agentAppCreator.chatWithUserId(message, updatedThreadId, appId, finalUserId);
                if (output.getAgentResponse() != null
                        && output.getAgentResponse().getStructuredReply() != null
                        && output.getAgentResponse().getStructuredReply().getFiles() != null) {
                    codeFileSaverUtil.writeFilesToLocal(
                            output.getAgentResponse().getStructuredReply().getFiles(), appId);
                    appVersionService.createVersionSnapshot(appId, AppVersionSourceEnum.GENERATED.getValue(),
                            "generated by agent task", null);
                }
                if (output.getAgentResponse() != null
                        && output.getAgentResponse().getCodeOptimizationInput() != null) {
                    agentTaskExecutor.submitOptimizationTask(
                            output.getAgentResponse().getCodeOptimizationInput(),
                            updatedThreadId,
                            appId,
                            finalUserId
                    );
                }
                agentTaskService.saveFinalOutput(taskId, output);
                agentTaskService.updateStatus(taskId, SUCCEEDED);
                log.info("Agent task succeeded, taskId={}, threadId={}, appId={}, userId={}",
                        taskId, updatedThreadId, appId, finalUserId);
            } catch (Exception e) {
                agentTaskService.markFailed(taskId, e);
                log.error("Agent task failed, taskId={}, threadId={}, appId={}, userId={}",
                        taskId, updatedThreadId, appId, finalUserId, e);
            }
        });

        AgentTask agentTask = agentTaskService.getByTaskId(taskId);
        return AgentTaskStatus.builder()
                .taskId(taskId)
                .threadId(updatedThreadId)
                .appId(appId)
                .taskStatus(AgentTaskStatusEnum.toApiValue(agentTask.getTaskStatus()))
                .message("任务已进入队列")
                .retryCount(agentTask.getRetryCount())
                .failType(agentTask.getFailType())
                .nextRetryTime(agentTask.getNextRetryTime())
                .createTime(agentTask.getCreateTime())
                .build();
    }

    @Scheduled(fixedDelay = 10000)
    public void retryFailedTasks() {
        String statusIndexKey = TASK_STATUS_INDEX_PREFIX + AgentFailTypeEnum.SYSTEM_RETRYABLE.getValue();
        Set<String> taskIds = stringRedisTemplate.opsForSet().members(statusIndexKey);
        if (taskIds == null || taskIds.isEmpty()) {
            return;
        }

        for (String taskId : taskIds) {
            AgentTask task = agentTaskRedisTemplate.opsForValue().get(AgentTaskConstant.AGENT_TASK_PREFIX + taskId);
            if (task == null) {
                continue;
            }
            if (!AgentTaskStatusEnum.RETRY_WAITING.getValue().equals(task.getTaskStatus())) {
                continue;
            }
            if (task.getRetryCount() >= 5) {
                continue;
            }
            if (task.getNextRetryTime() != null && task.getNextRetryTime().isAfter(LocalDateTime.now())) {
                continue;
            }
            autoRetry(task);
        }
    }

    private void autoRetry(AgentTask task) {
        agentTaskService.updateStatus(task.getTaskId(), AgentTaskStatusEnum.RETRY_WAITING);
        log.info("Auto retry task, taskId={}, threadId={}, appId={}, retryCount={}",
                task.getTaskId(), task.getThreadId(), task.getAppId(), task.getRetryCount());

        agentTaskExecutor.submitAgentTask(task.getTaskId(), () -> {
            try {
                agentTaskService.updateStatus(task.getTaskId(), AgentTaskStatusEnum.RUNNING);
                if (task.getTaskResult() == null || StrUtil.isBlank(task.getTaskResult().getIntentSummary())) {
                    throw new IllegalStateException("任务缺少重试上下文，无法自动重试");
                }
                SystemOutput output = agentAppCreator.chat(
                        task.getTaskResult().getIntentSummary(),
                        task.getThreadId(),
                        task.getAppId());
                agentTaskService.saveFinalOutput(task.getTaskId(), output);
            } catch (Exception e) {
                agentTaskService.markFailed(task.getTaskId(), e);
            }
        });
    }

    public void manualRetry(AgentTask task) {
        log.info("Manual retry task, taskId={}, threadId={}, appId={}, retryCount={}",
                task.getTaskId(), task.getThreadId(), task.getAppId(), task.getRetryCount());
        task.setRetryCount(0);
        task.setTaskStatus(AgentTaskStatusEnum.RETRY_WAITING.getValue());
        task.setNextRetryTime(LocalDateTime.now());
        agentTaskRedisTemplate.opsForValue().set(AgentTaskConstant.AGENT_TASK_PREFIX + task.getTaskId(), task);
        autoRetry(task);
    }

    private void validateUserInput(String input) {
        if (StrUtil.isBlank(input)) {
            throw new BusinessException("输入不能为空", ErrorCode.PARAMS_ERROR);
        }
        if (input.length() > MAX_INPUT_LENGTH) {
            throw new BusinessException("输入过长，请分段发送", ErrorCode.PARAMS_ERROR);
        }
        if (SensitiveWordHelper.contains(input)) {
            throw new BusinessException("输入包含不适宜内容", ErrorCode.PARAMS_ERROR);
        }
    }
}
